### ISSUE TITLE
About the accuracy mismatch using the example code

### ISSUE THREAD

**Issue by wsstriving** [fungtion/DANN#1]
Hi, 
      I ran the code (main.py) using the default settings, but only get ~53% accuracy on the target set (80% on the source set), is anything not set appropriately?
      Thanks.

Sam

**Comment by fungtion** [comment]
how many epochs you ran?

**Comment by wsstriving** [comment]
100 epochs

**Comment by fungtion** [comment]
Thank you, I really make a mistake, you can fix the error by replace `transform.RandomSizedCrop` with `transfrom.Resize`, and I will upload the fixed version later.

**Comment by wsstriving** [comment]
Thanks,  now the test accuracy on the target domain achieves amazing 90%, far more better than the paper. What about your own experiment?

**Comment by omg777** [comment]
@fungtion 
Hi, can you tell me what is the difference?

**Comment by fungtion** [comment]
@omg777  comparing with the original paper, I set $\lambda$ in domain classifier as 1, and use Adam instead of SGD optimizer

**Comment by omg777** [comment]
@fungtion What is $\lambda$ ?
and when I run main.py ,
in this line `class_output, domain_output = my_net(input_data=inputv_img, alpha=alpha)`
`ValueError: expected 4D input (got 2D input)
`
error occurs. How can I fix this?
(my settings: python2.7 , pytorch0.4.1)

**Comment by fungtion** [comment]
@omg777 `$\lambda$` means `alpha` in the main.py, `inputv_img` must be 4D (n, c, w, h), you'd better check the shape of your `inputv_img`

**Comment by jindongwang** [comment]
@omg777 @fungtion I also have the same problem. We didn't change your code, it runs and it get the results. Could you please check the code? The error is `class_output = self.class_classifier(feature)` of the model file.

**Comment by fungtion** [comment]
@jindongwang the same error `ValueError: expected 4D input (got 2D input)`?

**Comment by jindongwang** [comment]
@fungtion Try my code: https://github.com/jindongwang/transferlearning/tree/master/code/deep/DANN(RevGrad)

**Comment by fungtion** [comment]
@jindongwang I mean you got the same error `ValueError: expected 4D input (got 2D input)` ?

**Comment by jindongwang** [comment]
@fungtion Yes, but I fixed that in my code...

**Comment by fungtion** [comment]
@jindongwang Can you show me why you got the error when running my code, since I didn't meet the error before, thank you.

**Comment by jindongwang** [comment]
@fungtion I think it's the pytorch version. We are using 0.4.0, while you are using 0.3...

**Comment by fungtion** [comment]
@jindongwang Ok

**Comment by jindongwang** [comment]
@fungtion The problem is `BatchNorm2d` function. I change it to `BatchNorm1d` and it's fine. https://github.com/jindongwang/transferlearning/blob/master/code/deep/DANN(RevGrad)/main/model.py

**Comment by fungtion** [comment]
@jindongwang I see, I'll fix it, thank you.
