### ISSUE TITLE
ImportError: No module named dataset.data_loader

### ISSUE THREAD

**Issue by tjzjp** [fungtion/DANN#10]
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from dataset.data_loader import GetLoader
ImportError: No module named dataset.data_loader

I'm sorry. I met this problem and don't know how to solve it.

**Comment by fungtion** [comment]
You can add the root path of DANN to the system path by
```python
import sys
sys.path.append(ROOT_PATH_OF_DANN)
```
