### ISSUE TITLE
Loss of domain classification part

### ISSUE THREAD

**Issue by IpekUyguner** [fungtion/DANN#12]
Hi, I am trying to understand GRL effect. While training should i expect to see the domain classification loss decrease to some extent or should it stay around random guess( so that it makes possible domain generalization) 

Thanks!

**Comment by fungtion** [comment]
The domain classification and label classification affect each other during the training, so how the classification loss decreases will depend on the adversarial relationship between two domains, it actually decreases to some value when domain loss reaches convergence.
