### ISSUE TITLE
 err_t_domain and err_s_domain

### ISSUE THREAD

**Issue by InstantWindy** [fungtion/DANN#13]
Hi.  I refer to your network design and loss to train my dataset for this experiment. When traing the network, I try to output the total loss of  err_t_domain and err_s_domain, the total loss decreases a little at first and then remain unchanged. Thanks.

**Comment by fungtion** [comment]
If your data are similar to mnist and mnistm, you can try to adjust the lambda value.

**Comment by InstantWindy** [comment]
My source data and target data are pedestrians. The value of err_domain has always been 1.3863 and does not drop.

**Comment by fungtion** [comment]
Pedestrians are far more complex than digits, I think it may be underfitting in your experiment.

**Comment by InstantWindy** [comment]
Thank for your reply.  if the err_domain loss doesn't drop, it means my source data and target data are not similar?

**Comment by fungtion** [comment]
Underfitting means the model cannot transfer the information between source and target domain, either because of the data or your model.

**Comment by InstantWindy** [comment]
My task is not classification, but super resolution. I just use the super resolution network to extract features, and then input the features into the domain classification for discrimination.

**Comment by fungtion** [comment]
Oh, I think this network can only extract class level information, pixel information may be very difficult.

**Comment by InstantWindy** [comment]
Which network do you mean? super resolution network?

**Comment by fungtion** [comment]
DANN，I mean, it is not strong enough to transfer pixel information.

**Comment by InstantWindy** [comment]
Thanks.
