### ISSUE TITLE
Does domain Adaptation really help the training

### ISSUE THREAD

**Issue by Liujingxiu23** [fungtion/DANN#15]
I have confusions when using DANN in speech emotion style transfer. And I have two questions as below
1.for the domain classifier, what level of accuracy should we expected？ Will the domain-classifier-loss decline normally?
2.quetion as the title

**Comment by syu999-github** [comment]
Hello, I read this article recently and have the same problem as you. Although I read this article many times, I still don't know whether domain adaptation really helps the training. Do you still have this question now?

**Comment by syu999-github** [comment]
> I have confusions when using DANN in speech emotion style transfer. And I have two questions as below 1.for the domain classifier, what level of accuracy should we expected？ Will the domain-classifier-loss decline normally? 2.quetion as the title

Hello, I read this article recently and have the same problem as you. Although I read this article many times, I still don't know whether domain adaptation really helps the training. Do you still have this question now?

**Comment by Liujingxiu23** [comment]
@syu999-github  no, I have not get any conlusion, and still confused. But I have moved on to other methods for a long time.

**Comment by syu999-github** [comment]
@Liujingxiu23 Thank you very much for your reply. I think I need to consider how to do it next. Maybe I can move to other methods as you, hahaha~
