### ISSUE TITLE
alpha

### ISSUE THREAD

**Issue by kikiYa99** [fungtion/DANN#19]
您好，我想请问一下，程序里的alpha参数，是DANN图中反转层的lambda嘛

**Comment by fungtion** [comment]
If you mean [here](https://github.com/fungtion/DANN/blob/master/models/model.py#L38), yes

**Comment by kikiYa99** [comment]
yes！还想请问一下为什么在test中的alpha和训练模型的alpha是不一样的呢，test中的alpha怎么取呢？

**Comment by fungtion** [comment]
At the beginning of training, the domain classifier is not reliable to distinguish different domains, so we set a small value of alpha (lambda), like 0, and with the training progress, it becomes better, so the alpha will increase its value gradually to 1. In test, we don't need backward, so alpha is set to 0.

**Comment by kikiYa99** [comment]
明白了！太谢谢您了！
