### ISSUE TITLE
RuntimeError: output with shape [1, 28, 28] doesn't match the broadcast shape [3, 28, 28]

### ISSUE THREAD

**Issue by houchenyu** [fungtion/DANN#8]
When I run your code, I have met a error when executing `data_source = data_source_iter.next()`:

RuntimeError: output with shape [1, 28, 28] doesn't match the broadcast shape [3, 28, 28].

I have no idea why this error occurs. Could you please give some suggestions.
Besides, I'm using Python3.6 and Pytorch 1.0. My operating system is Ubuntu 16.04. Thanks.

**Comment by fungtion** [comment]
I have not tested it on pytorch 1.0 yet, but I have [transfrom the gray images into 3 channels]( https://github.com/fungtion/DANN/blob/master/models/model.py#L39), can you post the complete errors here?

**Comment by houchenyu** [comment]
> I have not tested it on pytorch 1.0 yet, but I have [transfrom the gray images into 3 channels](https://github.com/fungtion/DANN/blob/master/models/model.py#L39), can you post the complete errors here?

But there is no error on Windows10 with the same version of pytorch.

**Comment by fungtion** [comment]
I've no idea about it, and I'll test it with pytorch 1.0 on Ubuntu soon.

**Comment by houchenyu** [comment]
Traceback (most recent call last):
  File "/home/hou/桌面/DANN-master/train/main.py", line 98, in <module>
    data_source = data_source_iter.next()
  File "/home/hou/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/hou/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/hou/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/hou/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/hou/anaconda3/envs/py36/lib/python3.6/site-packages/torchvision/datasets/mnist.py", line 95, in __getitem__
    img = self.transform(img)
  File "/home/hou/anaconda3/envs/py36/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/home/hou/anaconda3/envs/py36/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 163, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/home/hou/anaconda3/envs/py36/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 208, in normalize
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
RuntimeError: output with shape [1, 28, 28] doesn't match the broadcast shape [3, 28, 28]

**Comment by houchenyu** [comment]
This is the complete error info. It seems wrong about `dataloader`

**Comment by fungtion** [comment]
I guess something wrong [here](https://github.com/fungtion/DANN/blob/master/dataset/data_loader.py#L26), some images are not converted to 3 channels as rgb.

**Comment by houchenyu** [comment]
Yes, I agree with you. But I have no idea about why it dosen't work.

**Comment by fungtion** [comment]
I built these codes on pytorch 0.4.0, python 2.7,  ubuntu 16.04, this could make any difference? I will test it soon.

**Comment by houchenyu** [comment]
Maybe it is not. According to the error ondo, there is a error about the source data loader, which is implementwd by in-place function. Therefore, Ithink this error is not caused by convertion.

**Comment by fungtion** [comment]
This error was caused by the shape mismatch between the `tensor` and `self.mean` in `F.normalize`,  which tensor was [1,28,28] and self.mean was [0.5, 0.5, 0.5], so the shape of self.mean implied that the tensor should be [3, *, *], instead of [1, *, *]. So I think there is something wrong with this input tensor.

**Comment by houchenyu** [comment]
`mnist` dataset consists of grey images which are 1 channel. Thus the input tensor is [1, *, *]. Indeed, you have implemented the self-defined loader `GetLoader` where you convert the input images to `RGB`. But this loader is used to load `mnist_m` dataset rather than `mnist` dataset. Therefore, there is nothing to do with `mnist` dataset. And input tensor of `mnist` is still [1,  *, *].

**Comment by houchenyu** [comment]
Ooooooh, finally, I run the code successfully. I add a new transform like this
```
img_transform1 = transforms.Compose([
    transforms.Resize(image_size),
    transforms.ToTensor(),
    transforms.Lambda(lambda x: x.repeat(3,1,1)),
    transforms.Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5))
])
```
And  I replace the original transform of source data `mnist` with `img_transform1`.  By do so, the `mnist` images can be converted to [3, *, *] tensors. I am curious about why the code is OK under your settings.
In my opinion, is there a difference about `torchvision.datasets.MNIST()` function between torch 0.4 and torch 1.0???

**Comment by fungtion** [comment]
Yes, you're right, input tensor of mnist is still [1, *, *]. The problem comes https://github.com/pytorch/vision/commit/21153802a3086558e9385788956b0f2808b50e51#diff-fc1f220b470714d05cf3ea6acf9fed59L204, where it used `zip` to return iterable object before, and [If multiple iterables are passed, iterator stops when shortest iterable is exhaused](https://www.programiz.com/python-programming/methods/built-in/zip), I think this is the reason that it ran well in my settings. After the zip was replaced by broadcasting, my codes failed because of shape mismatch.  I will fix it soon, thank you.

**Comment by FLHonker** [comment]
add `transforms.CenterCrop(),` after ` transforms.Resize` .
```
# load data
transform = transforms.Compose([
    transforms.Resize(224),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5)),
])
```

**Comment by RenMao1314** [comment]
Let me clarify, if the img has three channels, you should have three number for mean, for example, img is RGB, mean is [0.5, 0.5, 0.5], the normalize result is Rx0.5, Gx0.5, Bx0.5. If img is grey type that only one channel, so mean should be [0.5], the normalize result is R*0.5

**Comment by ShuuTsubaki** [comment]
> Ooooooh, finally, I run the code successfully. I add a new transform like this
> 
> ```
> img_transform1 = transforms.Compose([
>     transforms.Resize(image_size),
>     transforms.ToTensor(),
>     transforms.Lambda(lambda x: x.repeat(3,1,1)),
>     transforms.Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5))
> ])
> ```
> 
> And I replace the original transform of source data `mnist` with `img_transform1`. By do so, the `mnist` images can be converted to [3, *, *] tensors. I am curious about why the code is OK under your settings.
> In my opinion, is there a difference about `torchvision.datasets.MNIST()` function between torch 0.4 and torch 1.0???



>     transforms.Lambda(lambda x: x.repeat(3,1,1)),
>     transforms.Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5))

I received the fault , Can't pickle local object 'get_data_loaders.<locals>.<lambda>'.

**Comment by fungtion** [comment]
@ShuuTsubaki try new code under pytorch 1.0

**Comment by priteshgohil** [comment]
what should be the image_size in above code? I have image of 28x28.
When i set image size to 784, i get the following error.

> RuntimeError: size mismatch, m1: [128 x 1843968], m2: [784 x 128] at /opt/conda/conda-bld/pytorch_1556653099582/work/aten/src/TH/generic/THTensorMath.cpp:961

**Comment by fungtion** [comment]
@priteshgohil image_size = 28

**Comment by mvivekc** [comment]
Downgrading torch and torchvision to 0.2.0 and 0.2.1 solved this issue for me.

**Comment by JazzTheSaver** [comment]
> Downgrading torch and torchvision to 0.2.0 and 0.2.1 solved this issue for me.

Thanks So lot ! It helps me! BTW , Mine is  pytorch 1.1.0 + win10 , work with torchvision 0.2.0

**Comment by MohanaMeher** [comment]
I'm working on Ubuntu 16.04 version and using torch version 1.3.1
It's that MNIST data set consists of grey images.  

`transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5)),
])
`

**can be changed to** 

`transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])`

**Comment by MohanaMeher** [comment]
I'm working on Ubuntu 16.04 version and using torch version 1.3.1
It's that MNIST data set consists of grey images.

transform = transforms.Compose([ transforms.ToTensor(), transforms.Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5)), ])

can be changed to

transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])

**Comment by aourednik** [comment]
> I'm working on Ubuntu 16.04 version and using torch version 1.3.1
> It's that MNIST data set consists of grey images.
> 
> `transform = transforms.Compose([ transforms.ToTensor(), transforms.Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5)), ]) `
> 
> **can be changed to**
> 
> `transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])`

This solved the problem for me

**Comment by ferb2015** [comment]
img_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize([0.5], [0.5])
])
dataset = MNIST('./data', transform=img_transform)
